# log level -> TRACE  <  DEBUG  <  INFO  <  WARN  <  ERROR
# http://logback.qos.ch/manual/layouts.html
logging:
  level:
    root: info
  file:
    name: ./logs/local-log.log
    max-size: 1MB
    max-history: 30
  pattern:
    #    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %M %logger{35} - %msg%n"
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    file: "%-5level %d{yyyy-MM-dd HH:mm:ss}[%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    rolling: ./logs/local-log-%d{yyyy-MM-dd-HH-mm-ss}_%i.log.gz
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: sejong
    key-store-type: PKCS12
    key-alias: sejong-ssl
  http2:
    enabled: true
  port: 8443
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    group: local
  datasource:
    url: jdbc:mariadb://14.63.169.44:3306/spring_boot_quartz_cluster?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MariaDB103Dialect

channel: mychannel
call-base-url: https://14.63.169.44:8443/v1/

app:
  snapshot:
    # api 서버에서 batch insert 할때 한번에 insert 할 수량
    batchinsert-count: 10000
  vote:
    # 블록체인에서 한번에 조회할 페이지 사이즈 (st 목록)
    stlist-pagesize: 3000
  delimiter:
    # 펀드아이디에 무엇을 붙여야 st 토큰명이 되나? (and 체인코드명)
    st: st