logging:
  level:
    root: info
    net.sejongtelecom.testmid: info
  file:
    path: /home/ubuntu/app/log
    max-history: 30
server:
  port: 8083
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    group: dev
  datasource:
    url: jdbc:mariadb://14.63.169.44:3306/FABDB
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: password
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MariaDB103Dialect